version: '3.3'

services:
  web-app:
    build: web-app
    ports:
      - '8080:3000'
    depends_on:
      - server

  server:
    build: server
    env_file: .env
    ports:
      - '3000:3000'
    links:
      - database
    depends_on:
      - database

  database:
    image: excellalabs/mongo:3.4.7
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
     - '/tmp/minimal-mean-db:/data/db'